/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import herramientas.Diccionario;
import herramientas.LeerEscribirArchivos;
import herramientas.Pila;
import java.util.HashMap;

/**
 *
 * @author RAFAEL
 */
public class Logueo extends javax.swing.JFrame {

    private String nick, contraseña, contraseñaAsciiPila, nombrePila, datos;
    private Diccionario diccionario;
    private HashMap mapa;
    private Pila pila;
    private int capa1, capa2, capa3, capa4, capa1Pila, capa2Pila, capa3Pila, capa4Pila;
    private boolean acceso;

    /**
     * Creates new form Logueo
     */
    public Logueo() {
        initComponents();
        diccionario = new Diccionario();
        diccionario.agregarDatos("Rafa17/123456789");
        diccionario.crearArchivo();
        acceso = false;
        this.setSize(600, 400);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JPasswordField();
        labelAdvertencia = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        botonIngresar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Logueo");
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Nickname:");
        jPanel2.add(jLabel1);

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNombre.setText("Rafa17");
        jPanel2.add(txtNombre);

        jPanel1.add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Contraseña:");
        jPanel3.add(jLabel2);

        txtContraseña.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtContraseña.setText("123456789");
        jPanel3.add(txtContraseña);

        jPanel1.add(jPanel3);
        jPanel1.add(labelAdvertencia);

        jPanel4.setLayout(new java.awt.GridLayout(1, 2));

        botonIngresar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonIngresar.setText("Ingresar");
        botonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarActionPerformed(evt);
            }
        });
        jPanel4.add(botonIngresar);

        botonSalir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        jPanel4.add(botonSalir);

        jPanel1.add(jPanel4);

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarActionPerformed
        // TODO add your handling code here:
        String nombre = txtNombre.getText();
        String contraseña = txtContraseña.getText(), contraseñaAscii = diccionario.transformarAscii(contraseña);

        if (nombre.equals("") || contraseña.equals("")) {
            labelAdvertencia.setText("Porfavor llene ambos campos");
        } else {
            mapa = diccionario.obtenerDatosArchivo();

            if (contraseña.length() > 3) {
                contraseñaAscii = contraseñaAscii.substring(0, 7);
            }
            
            capa1 = diccionario.hashModulo(Integer.parseInt(contraseñaAscii));
            capa2 = diccionario.hashModulo((int) capa1);
            capa3 = diccionario.hashModulo((int) capa2);
            capa4 = diccionario.hashModulo((int) capa3);

            int llave = (int) capa4;

            pila = (Pila) mapa.get(llave);
            if (pila != null) {
                capa4Pila = Integer.parseInt(pila.pop());
                capa3Pila = Integer.parseInt(pila.pop());
                capa2Pila = Integer.parseInt(pila.pop());
                capa1Pila = Integer.parseInt(pila.pop());
                datos = pila.pop();
                nombrePila = datos.toString().split("/")[0];
                contraseñaAsciiPila = datos.toString().split("/")[1];
                
                if (capa4 == capa4Pila) {
                    System.out.println("Capa 4 superada");
                    if (capa3 == capa3Pila) {
                        System.out.println("Capa 3 superada");
                        if (capa2 == capa2Pila) {
                            System.out.println("Capa 2 superada");
                            if (capa1 == capa1Pila) {
                                System.out.println("Capa 1 superada");
                                if (diccionario.transformarAscii(contraseña).equals(contraseñaAsciiPila.toString()) && nombre.equals(nombrePila.toString())) {
                                    acceso = true;
                                    this.dispose();
                                } else {
                                    labelAdvertencia.setText("Nick o contraseña incorrectos");
                                }
                            } else {
                                System.out.println("NO SE SUPERO LA CAPA 1");
                                labelAdvertencia.setText("Nick o contraseña incorrectos");
                            }
                        } else {
                            System.out.println("NO SE SUPERO LA CAPA 2");
                            labelAdvertencia.setText("Nick o contraseña incorrectos");
                        }
                    } else {
                        System.out.println("NO SE SUPERO LA CAPA 3");
                        labelAdvertencia.setText("Nick o contraseña incorrectos");
                    }
                } else {
                    System.out.println("NO SE SUPERO LA CAPA 4");
                    labelAdvertencia.setText("Nick o contraseña incorrectos");
                }

            } else {
                labelAdvertencia.setText("Nick o contraseña incorrectos");
            }
        }

    }//GEN-LAST:event_botonIngresarActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_botonSalirActionPerformed

    public boolean isAcceso() {
        return acceso;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIngresar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labelAdvertencia;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
